vich_uploader:
    db_driver: orm

    mappings:
        news_file:
            uri_prefix: /index.php/app/news/files
            upload_destination: '%kernel.project_dir%/files/news'
            namer:
                service: Vich\UploaderBundle\Naming\Base64Namer
                options: { length: 10 }
